"""init schema

Revision ID: bd8236b28a6c
Revises: 
Create Date: 2025-08-10 15:20:18.783718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'bd8236b28a6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    
    op.create_table('insurer',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('insurer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('line_of_business', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.CheckConstraint("line_of_business in ('health','motor')", name='ck_lob'),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_version',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_document',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('policy_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_chunk',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('policy_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('page_from', sa.Integer(), nullable=True),
    sa.Column('page_to', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('policyChunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
   sa.Column('embedding', Vector(1536), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['policy_document.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_chunk')
    op.drop_table('policy_document')
    op.drop_table('policy_version')
    op.drop_table('product')
    op.drop_table('insurer')
    op.execute('DROP INDEX IF EXISTS idx_policy_chunk_embedding')
    # ### end Alembic commands ###
