"""add UIN to policy_version

Revision ID: c76d69435526
Revises: bd8236b28a6c
Create Date: 2025-08-15 17:21:27.981326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76d69435526'
down_revision: Union[str, Sequence[str], None] = 'bd8236b28a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('policy_version', sa.Column('uin', sa.String(), nullable=False))
    op.create_index('ix_policy_version_product', 'policy_version', ['product_id'], unique=False)
    op.create_unique_constraint(None, 'policy_version', ['uin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policy_version', type_='unique')
    op.execute('DROP INDEX IF EXISTS idx_policy_chunk_embedding')
    op.drop_column('policy_version', 'uin')
    op.create_index(op.f('idx_policy_chunk_policy'), 'policy_chunk', ['policy_version_id'], unique=False)
    op.create_index(op.f('idx_policy_chunk_embedding'), 'policy_chunk', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
